<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="simple_gripper">

  <!-- 通过宏定义夹爪 -->
  <xacro:macro name="simple_gripper" params="gripper_name parent_link finger_length finger_width finger_thickness *origin">
    
    <!-- 夹爪基座 -->
    <link name="${gripper_name}_base">
      <visual>
        <geometry>
          <box size="0.04 0.04 0.02"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.04 0.04 0.02"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
      </inertial>
    </link>

    <!-- 左手指 -->
    <link name="${gripper_name}_left_finger">
      <visual>
        <geometry>
          <box size="${finger_width} ${finger_length} ${finger_thickness}"/>
        </geometry>
        <origin xyz="0 0 ${finger_thickness/2}" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="${finger_width} ${finger_length} ${finger_thickness}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001"/>
      </inertial>
    </link>

    <!-- 右手指 -->
    <link name="${gripper_name}_right_finger">
      <visual>
        <geometry>
          <box size="${finger_width} ${finger_length} ${finger_thickness}"/>
        </geometry>
        <origin xyz="0 0 ${finger_thickness/2}" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="${finger_width} ${finger_length} ${finger_thickness}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001"/>
      </inertial>
    </link>

    <!-- 左手指关节 -->
    <joint name="${gripper_name}_left_finger_joint" type="prismatic">
      <parent link="${gripper_name}_base"/>
      <child link="${gripper_name}_left_finger"/>
      <origin xyz="-0.03 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/> <!-- 平移方向 -->
      <limit effort="0.0" lower="0.0" upper="0.03" velocity="0.0"/>
    </joint>

    <!-- 右手指关节 -->
    <joint name="${gripper_name}_right_finger_joint" type="prismatic">
      <parent link="${gripper_name}_base"/>
      <child link="${gripper_name}_right_finger"/>
      <origin xyz="0.03 0 0" rpy="0 0 0"/>
      <axis xyz="-1 0 0"/> <!-- 平移方向 -->
      <limit effort="0.0" lower="0.0" upper="0.03" velocity="0.0"/>
    </joint>

    <!-- 将基座固定到父链上 -->
    <joint name="fixed_${gripper_name}_base" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent_link}"/>
      <child link="${gripper_name}_base"/>
    </joint>

  </xacro:macro>

</robot>
